var DB2 = {
    "spirits" :
        [{
            "nr": "7557801",
            "artikelid": "796503",
            "varnummer": "75578",
            "namn": "R6",
            "namn2": "Riserva",
            "prisinklmoms": "149.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2013-10-01",
            "slutlev": " ",
            "varugrupp": "Rött vin",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "",
            "ursprunglandnamn": "Kroatien",
            "producent": "Vina Bibich",
            "leverantor": "Armano's First Class Products ",
            "argang": "2010",
            "provadargang": "",
            "alkoholhalt": "13%",
            "modul": "",
            "kvantitet": "20",
            "sortiment": "BS",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "7559802",
            "artikelid": "799834",
            "varnummer": "75598",
            "namn": "Boeckel",
            "namn2": "Riesling Vendanges Tardives",
            "prisinklmoms": "301.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2013-11-01",
            "slutlev": " ",
            "varugrupp": "Vitt vin, Sött",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "Alsace",
            "ursprunglandnamn": "Frankrike",
            "producent": "Émile Boeckel",
            "leverantor": "Varbergs Vingrossist AB",
            "argang": "2006",
            "provadargang": "",
            "alkoholhalt": "12%",
            "modul": "",
            "kvantitet": "10",
            "sortiment": "BS",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "7563601",
            "artikelid": "783836",
            "varnummer": "75636",
            "namn": "Myskhako",
            "namn2": "Riesling Reserve",
            "prisinklmoms": "276.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2013-09-02",
            "slutlev": " ",
            "varugrupp": "Vitt vin",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "",
            "ursprunglandnamn": "Ryssland",
            "producent": "JSC Winery Myskhako",
            "leverantor": "Tre Svampar Import Export",
            "argang": "2009",
            "provadargang": "",
            "alkoholhalt": "13.5%",
            "modul": "",
            "kvantitet": "55",
            "sortiment": "BS",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "7564301",
            "artikelid": "796652",
            "varnummer": "75643",
            "namn": "Radici",
            "namn2": "Fiano di Avellino",
            "prisinklmoms": "169.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2013-10-01",
            "slutlev": " ",
            "varugrupp": "Vitt vin",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "Kampanien, Fiano di Avellino",
            "ursprunglandnamn": "Italien",
            "producent": "Mastroberardino",
            "leverantor": "Tryffelsvinet AB",
            "argang": "2012",
            "provadargang": "",
            "alkoholhalt": "13.5%",
            "modul": "",
            "kvantitet": "5",
            "sortiment": "BS",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "7567801",
            "artikelid": "793851",
            "varnummer": "75678",
            "namn": "Liberty School",
            "namn2": "Zinfandel",
            "prisinklmoms": "189.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2013-10-01",
            "slutlev": " ",
            "varugrupp": "Rött vin",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "Kalifornien",
            "ursprunglandnamn": "USA",
            "producent": "Hope Family Wines",
            "leverantor": "Haugen-Gruppen AB",
            "argang": "2010",
            "provadargang": "",
            "alkoholhalt": "13.5%",
            "modul": "",
            "kvantitet": "87",
            "sortiment": "BS",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "7577701",
            "artikelid": "796730",
            "varnummer": "75777",
            "namn": "Quinta Apolonia",
            "namn2": "Belondrade",
            "prisinklmoms": "149.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2013-10-01",
            "slutlev": " ",
            "varugrupp": "Vitt vin",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "Castilla y León",
            "ursprunglandnamn": "Spanien",
            "producent": "Belondrade y Lurton",
            "leverantor": "Ametller Scandinavia AB",
            "argang": "2013",
            "provadargang": "",
            "alkoholhalt": "13.5%",
            "modul": "",
            "kvantitet": "20",
            "sortiment": "BS",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "7509501",
            "artikelid": "797293",
            "varnummer": "75095",
            "namn": "Tendance Casanova",
            "namn2": "Blanc",
            "prisinklmoms": "171.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2013-10-01",
            "slutlev": " ",
            "varugrupp": "Vitt vin",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "Korsika",
            "ursprunglandnamn": "Frankrike",
            "producent": "Vignerons d'Aghione",
            "leverantor": "Octopus Group Nordic AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "12%",
            "modul": "",
            "kvantitet": "33",
            "sortiment": "BS",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "7509401",
            "artikelid": "797290",
            "varnummer": "75094",
            "namn": "Tendance Casanova",
            "namn2": "Gris",
            "prisinklmoms": "171.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2013-10-01",
            "slutlev": " ",
            "varugrupp": "Rosévin",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "Korsika",
            "ursprunglandnamn": "Frankrike",
            "producent": "Vignerons d'Aghione",
            "leverantor": "Octopus Group Nordic AB",
            "argang": "2012",
            "provadargang": "",
            "alkoholhalt": "12%",
            "modul": "",
            "kvantitet": "98",
            "sortiment": "BS",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "750002",
            "artikelid": "312420",
            "varnummer": "7500",
            "namn": "Lanson",
            "namn2": "Black Label",
            "prisinklmoms": "194.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2008-04-01",
            "slutlev": " ",
            "varugrupp": "Mousserande vin, Vitt torrt",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "Champagne",
            "ursprunglandnamn": "Frankrike",
            "producent": "Lanson",
            "leverantor": "Chris-Wine AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "12.5%",
            "modul": "",
            "kvantitet": "65",
            "sortiment": "BS",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "153614",
            "artikelid": "792739",
            "varnummer": "1536",
            "namn": "Heineken",
            "namn2": "",
            "prisinklmoms": "15.30",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2013-10-01",
            "slutlev": " ",
            "varugrupp": "Öl, Ljus lager",
            "forpackning": "Burk",
            "forslutning": "",
            "ursprung": "",
            "ursprunglandnamn": "Internationellt märke",
            "producent": "Spendrups",
            "leverantor": "Spendrups Bryggeri AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "5%",
            "modul": "",
            "kvantitet": "29",
            "sortiment": "BS",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "147615",
            "artikelid": "765340",
            "varnummer": "1476",
            "namn": "Norrlands Guld",
            "namn2": "Ljus",
            "prisinklmoms": "9.90",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2013-09-02",
            "slutlev": " ",
            "varugrupp": "Öl, Ljus lager",
            "forpackning": "Burk",
            "forslutning": "",
            "ursprung": "",
            "ursprunglandnamn": "Sverige",
            "producent": "Spendrups",
            "leverantor": "Spendrups Bryggeri AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "4.7%",
            "modul": "",
            "kvantitet": "21",
            "sortiment": "FS",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "1139212",
            "artikelid": "508393",
            "varnummer": "11392",
            "namn": "Arboga 10,2",
            "namn2": "",
            "prisinklmoms": "19.90",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2011-10-24",
            "slutlev": " ",
            "varugrupp": "Öl, Ljus lager",
            "forpackning": "Burk",
            "forslutning": "",
            "ursprung": "Stockholms län, Stockholms stad",
            "ursprunglandnamn": "Sverige",
            "producent": "Three Towns Ind Brewers",
            "leverantor": "Galatea Spirits AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "10.2%",
            "modul": "",
            "kvantitet": "20",
            "sortiment": "FS",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "147403",
            "artikelid": "402946",
            "varnummer": "1474",
            "namn": "Swedish Elk Brew",
            "namn2": "",
            "prisinklmoms": "11.40",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2009-10-01",
            "slutlev": " ",
            "varugrupp": "\u00c3\u2013l, Ljus lager",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "",
            "ursprunglandnamn": "Sverige",
            "producent": "Kopparbergs\/Sofiero Bryggeri",
            "leverantor": "KopparbergsSofiero Bryggeri",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "7.5%",
            "modul": "",
            "kvantitet": "11",
            "sortiment": "FS",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "8958903",
            "artikelid": "716259",
            "varnummer": "89589",
            "namn": "Wisby Stout",
            "namn2": "",
            "prisinklmoms": "20.20",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2012-12-01",
            "slutlev": " ",
            "varugrupp": "Öl, Porter och Stout",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "Gotlands län, Gotland",
            "ursprunglandnamn": "Sverige",
            "producent": "Gotlands Bryggeri",
            "leverantor": "Spendrups Bryggeri AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "5%",
            "modul": "",
            "kvantitet": "27",
            "sortiment": "BS",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "8873203",
            "artikelid": "755964",
            "varnummer": "88732",
            "namn": "Madness IPA",
            "namn2": "",
            "prisinklmoms": "48.80",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2013-05-02",
            "slutlev": " ",
            "varugrupp": "Öl, Ale",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "",
            "ursprunglandnamn": "Storbritannien",
            "producent": "Wild Beer Co",
            "leverantor": "World Beer Trading KB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "6.8%",
            "modul": "",
            "kvantitet": "36",
            "sortiment": "BS",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "8872803",
            "artikelid": "770518",
            "varnummer": "88728",
            "namn": "Groundbreaker",
            "namn2": "Unfiltered Lager",
            "prisinklmoms": "19.90",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2013-07-01",
            "slutlev": " ",
            "varugrupp": "Öl, Ljus lager",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "Uppsala län, Uppsala kommun",
            "ursprunglandnamn": "Sverige",
            "producent": "Train Station Brewery AB",
            "leverantor": "Train Station Brewery AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "5.3%",
            "modul": "",
            "kvantitet": "99",
            "sortiment": "TSLS",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "8115806",
            "artikelid": "44469",
            "varnummer": "81158",
            "namn": "Guinness",
            "namn2": "",
            "prisinklmoms": "75",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2003-11-01",
            "slutlev": " ",
            "varugrupp": "Öl, Porter och Stout",
            "forpackning": "Fat",
            "forslutning": "",
            "ursprung": "",
            "ursprunglandnamn": "Irland",
            "producent": "Guinness",
            "leverantor": "Carlsberg Sverige AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "4.2%",
            "modul": "",
            "kvantitet": "18",
            "sortiment": "BS",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "8650404",
            "artikelid": "346896",
            "varnummer": "86504",
            "namn": "Absolut Vodka",
            "namn2": "",
            "prisinklmoms": "240.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2008-10-01",
            "slutlev": " ",
            "varugrupp": "Okryddad sprit",
            "forpackning": "12 fl á 50 ml",
            "forslutning": "",
            "ursprung": "Skåne län, Kristianstads kommun",
            "ursprunglandnamn": "Sverige",
            "producent": "V&S",
            "leverantor": "Pernod Ricard Sweden AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "40%",
            "modul": "",
            "kvantitet": "57",
            "sortiment": "BS",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "9501",
            "artikelid": "215164",
            "varnummer": "95",
            "namn": "Stolichnaya",
            "namn2": "Premium Vodka",
            "prisinklmoms": "215.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2006-10-02",
            "slutlev": " ",
            "varugrupp": "Okryddad sprit",
            "forpackning": "Flaska",
            "forslutning": "Skruvkapsyl",
            "ursprung": "",
            "ursprunglandnamn": "Internationellt märke",
            "producent": "SPI Spirits Limited",
            "leverantor": "Edrington Sweden AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "38%",
            "modul": "",
            "kvantitet": "36",
            "sortiment": "FS",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "10801",
            "artikelid": "185",
            "varnummer": "108",
            "namn": "Smirnoff",
            "namn2": "",
            "prisinklmoms": "219.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "1993-10-01",
            "slutlev": " ",
            "varugrupp": "Okryddad sprit",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "",
            "ursprunglandnamn": "Storbritannien",
            "producent": "Pierre Smirnoff Company",
            "leverantor": "Diageo Sweden AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "37.5%",
            "modul": "",
            "kvantitet": "11",
            "sortiment": "FS",
            "ekologisk": "0",
            "koscher": "0"
        }]
};